# Generated by Django 3.1.2 on 2021-03-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('outofdelevery', 'Out_of_Delevery'), ('Delivered', 'Delivered')], max_length=30, null=True),
        ),
    ]
